title: PetBite
description: Organization page for PetBite
remote_theme: pages-themes/slate@v0.2.0
google_analytics:
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/PetBite/app
plugins:
- jekyll-remote-theme
